### ISSUE TITLE
[BUG]Cannot read properties of null (reading 'version') 

### ISSUE THREAD

**Issue by mikehappi** [budgetbee/budgetbee#40]
Cannot read properties of null (reading 'version') TypeError: Cannot read properties of null (reading 'version') at getUser
<img width="1013" alt="Screen Shot 2023-07-25 at 11 16 14" src="https://github.com/budgetbee/budgetbee/assets/30312394/d84684c4-a508-4aff-8619-a9d404bb6049">

**Comment by Pelukosa** [comment]
Fixed in [version v.0.2.2](https://github.com/budgetbee/budgetbee/releases/tag/v0.2.2)

**Comment by rickette** [comment]
Hi, repoping the issue here.
I downloaded the @latest image this morning and still get this exact issue :
![BudgetBee](https://github.com/budgetbee/budgetbee/assets/11071486/20ad33aa-02f0-4570-af00-7f92ac9eb688)
